### ISSUE TITLE
Emulator

### ISSUE THREAD

**Issue by aleeusgr** [aleeusgr/potential-robot#37]
- [ ] https://github.com/aleeusgr/potential-robot/pull/42
- [x] https://github.com/aleeusgr/potential-robot/pull/38
- [x] https://github.com/spacebudz/lucid/blob/main/src/provider/emulator.ts
- [x] [matching_keyhash](https://github.com/spacebudz/lucid/blob/main/src/examples/matching_keyhash.ts)
- [ ] [RTFM](https://iohk.io/en/blog/posts/2021/09/07/no-surprises-transaction-validation-part-2/)

**Comment by aleeusgr** [comment]
> 220  submitTx(tx: Transaction): Promise<TxHash> {
>     /*
         Checks that are already handled by the transaction builder:
           - Fee calculation
           - Phase 2 evaluation
           - Input value == Output value (including mint value)
           - Min ada requirement
           - Stake key registration deposit amount
           - Collateral
```

**Comment by rjharmon** [comment]
Plus the helios-to-lucid-txn-building example at https://github.com/spacebudz/lucid/blob/main/src/examples/matching_keyhash.ts

**Comment by aleeusgr** [comment]
Lucid: create Cardano transactions and off-chain code for your Plutus contracts in JavaScript, Deno and Node.js.
